
package vista;

/**
 *
 * @author ALVIS
 */
public class MenuAforosIni extends javax.swing.JPanel {

    private MenuAforos padre;
    /**
     * Creates new form MenuAforosIni
     */
    public MenuAforosIni(MenuAforos p) {
        initComponents();
        padre = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(180, 290, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MadecLogo2.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ComunicacionGUI obj = new ComunicacionGUI();
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
        padre.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
