/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import conexion.AforoJPA;
import entidad.Aforo;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import static java.util.logging.Logger.global;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.WindowConstants;

/**
 *
 * @author ALVIS
 */
public class MenuAforos extends javax.swing.JFrame {

    int i =0;
    
    private List<Aforo> aforos;
    private AforoJPA aforoJPA;
    private Aforo aforo;
    
    Dimension tam;
    
    public MenuAforos(Dimension size) {
        
        initComponents();
        cargarInicio();
        aforos = new ArrayList<Aforo>();
        aforoJPA = new AforoJPA();
        aforos = aforoJPA.ListarAforos();
        
        setTitle("MADECSOFT");
        setSize(size);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png")));
        
        ButtonGroup bg = new ButtonGroup();
        JRadioButtonMenuItem[] radioAction = new JRadioButtonMenuItem[aforos.size()+1];
        for(i=0; i<aforos.size();i++){
            radioAction[i] = new JRadioButtonMenuItem(aforos.get(i).getNombre());
            radioAction[i].setName(aforos.get(i).getIdaforo().toString());
            bg.add(radioAction[i]);
            
            radioAction[i].addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent arg0) {
                    AforoSelected(arg0.getSource().toString().substring(arg0.getSource().toString().indexOf("[")+1, arg0.getSource().toString().indexOf(",")));                    
                }
            });
            fileMenu.add(radioAction[i]);            
        }
       
    }

    public void cargarInicio() {
        this.getContentPane().removeAll();
        MenuAforosIni pan = new MenuAforosIni(this);
        this.getContentPane().add(pan);
        pan.updateUI();
        this.repaint();
    }
    
    public void AforoSelected(String ID) {
        this.getContentPane().removeAll();
        AforoPanel pan = new AforoPanel(ID, this);
        this.getContentPane().add(pan);
        pan.updateUI();
    }
    
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MADECSOFT V1.0");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, "card2");

        jMenuBar2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MADECSOFT V1.0", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_BOTTOM));

        fileMenu.setText("LISTA DE AFOROS");
        jMenuBar2.add(fileMenu);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        final Dimension tam = null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAforos(tam).setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
